baseURL = "https://tayyipk.github.io/p2/"
title = "My Site"
theme = "academic"
publishDir = "docs"
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.highlight]
    style = "github" # Code highlighting